### ISSUE TITLE
The tracker not working

### ISSUE THREAD

**Issue by Maximm6987** [keluokeda/hs_tracker#10]
We can play without it but I really like what you made here, it's too bad it doesn't work now.

**Comment by keluokeda** [comment]
it can use now

**Comment by Maximm6987** [comment]
Thank you!!!

**Comment by SapYG** [comment]
![icon_29](https://github.com/keluokeda/hs_tracker/assets/137411778/79ebdf7a-04ae-4cb5-a5d4-080879423ed5)
You are the best developer. Thank you for your kindness and sincerity.
