### ISSUE TITLE
Failed to fetch data from server

### ISSUE THREAD

**Issue by Maximm6987** [keluokeda/hs_tracker#2]
This happens upon sync card data. Is there a solution?

Thanks a lot

EDIT: manual input of the json version solved this part.

**Comment by Maximm6987** [comment]
Also I guess this doesn't work on android 11?

**Comment by keluokeda** [comment]
I fix it now,use new version 1.2.6 and try it again

**Comment by Maximm6987** [comment]
Great it works now. Since you can see the opponent's graveyard, maybe make a tab for their deck, like in the arcane tracker.
